on:
  push:
    branches:
      - main
  workflow_dispatch:

name: publish docker

permissions:
  packages: write
  contents: write

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      
      - name: Clone jsonnet repository
        uses: actions/checkout@v4
        with:
          repository: 'google/jsonnet'
          path: 'jsonnet'
      - name: build & push to GitHub Container Registry
        working-directory: jsonnet
        run: |
          value=$(cat ../incr)
          TAG="ghcr.io/${{ github.repository }}:$(git describe --tags $(git rev-list --tags --max-count=1)).${value}"
          echo "TAG: $TAG"
          docker build -t "${TAG}" .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ github.actor }}" --password-stdin ghcr.io
          docker push "${TAG}"
        env:
          DOCKER_BUILDKIT: 1
      - name: push new incr value
        run: |
          value=$(cat incr)
          new_value=$((value + 1))
          echo $new_value > incr
          git add incr
          git config user.name  "actions-user"
          git config user.email "action@github.com"
          git commit -m "increment file"

