on:
  push:
    branches:
      - main
    paths:
      - jsonnet-version
  workflow_dispatch:

name: publish docker

permissions:
  packages: write
  contents: write

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          path: 'root'

      - name: Clone jsonnet repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: 'google/jsonnet'
          path: 'jsonnet'
      - name: build & push to GitHub Container Registry
        working-directory: jsonnet
        run: |
          value=$(cat ../root/incr)
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo $latest_tag > ../root/jsonnet-version # for renovate
          TAG="ghcr.io/${{ github.repository }}:$latest_tag.$value"
          echo "TAG: $TAG"
          docker build -t "${TAG}" .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ github.actor }}" --password-stdin ghcr.io
          docker push "${TAG}"
        env:
          DOCKER_BUILDKIT: 1
      - name: push new incr value
        working-directory: root
        run: |
          value=$(cat incr)
          new_value=$((value + 1))
          echo $new_value > incr
          git add incr
          git config user.name  "actions-user"
          git config user.email "action@github.com"
          git commit -m "increment file"
          git push origin HEAD

